build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant App: Disk Swap"
  org.opencontainers.image.description: "Flash HA OS to any USB device directly from Home Assistant."
  org.opencontainers.image.source: "https://github.com/eliav2/ha-disk-swap"
  org.opencontainers.image.licenses: "MIT"
